global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'jaxrs'
    metrics_path: '/metrics'
    static_configs:
        - targets: ['host.docker.internal:9101']

  - job_name: 'springmvc'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'datarest'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
